### ISSUE TITLE
Error in PIPELINE when publishing the model

### ISSUE THREAD

**Issue by CESARDELATORRE** [CESARDELATORRE/Easy-AutoML-MLOps#7]
[2020-06-07 04:44:51Z] RunId for the model output model_data is 6de459a9-8116-4351-a946-fa2435399627_4
[2020-06-07 04:45:20Z] **Failed to update outputs and mark job as failed. Error: The specified block list is invalid**., stack_trace:    at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteAsyncInternal[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)
   at Microsoft.WindowsAzure.Storage.Blob.BlobWriteStream.CommitAsync()
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.UploadFromStreamAsyncHelper(Stream source, Nullable`1 length, AccessCondition accessCondition, BlobRequestOptions options, OperationContext operationContext, IProgress`1 progressHandler, CancellationToken cancellationToken)
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.UploadFromStreamAsyncHelper(Stream source, Nullable`1 length, AccessCondition accessCondition, BlobRequestOptions options, OperationContext operationContext, CancellationToken cancellationToken)
   at Microsoft.RelInfra.Storage.AzureBlobStorage.UploadStreamWithTypeAsync(String containerName, String resourceId, Stream stream, String contentType) in d:\dbs\sh\Ae\0513_144959\cmd\n\src\aether\platform\RelInfra\RelInfra.Storage.Library\src\Storage\AzureBlobStorage.cs:line 1615
   at Microsoft.RelInfra.Storage.AzureBlobStorage.UploadStreamAsync(String containerName, String resourceId, Stream stream) in d:\dbs\sh\Ae\0513_144959\cmd\n\src\aether\platform\RelInfra\RelInfra.Storage.Library\src\Storage\AzureBlobStorage.cs:line 1569
   at Microsoft.Aether.BlueBox.Clouds.Common.RunOutputUploader.UploadToAzureBlobStorageAsync(AzureBlobReference blobReference, Stream stream, String contentType, WorkspaceIdentity workspaceIdentity, IDataStoreClient dataStoreClient, CounterManager counterManager, CreatedBy createdBy) in d:\dbs\sh\Ae\0518_162850\cmd\1k\src\aether\platform\backendV2\BlueBox\Clouds\Clouds.Common\RunOutputUploader.cs:line 119
   at Microsoft.Aether.BlueBox.Clouds.Common.RunOutputUploader.UploadFileWithUriAsync(CloudModuleOutputExecutionInfo outputInfo, Uri uri, WorkspaceIdentity workspaceIdentity, IDataStoreClient dataStoreClient, CounterManager counterManager, ICommonLogger logger, String executionDirectory, AzureSasUriClient sasClient, CreatedBy createdBy) in d:\dbs\sh\Ae\0518_162850\cmd\1k\src\aether\platform\backendV2\BlueBox\Clouds\Clouds.Common\RunOutputUploader.cs:line 79
   at Microsoft.Aether.AutoMLCloud.Service.JobProcessor.UpdateOutputsAsync(AutoMLJobMetadata job) in d:\dbs\sh\Ae\0518_162850\cmd\g\src\aether\platform\backendV2\BlueBox\Clouds\AutoMLCloud\Service\JobProcessor.cs:line 664
   at Microsoft.Aether.AutoMLCloud.Service.JobProcessor.CheckRunStatusAsync(AutoMLJobMetadata job, RunDto runDto) in d:\dbs\sh\Ae\0518_162850\cmd\g\src\aether\platform\backendV2\BlueBox\Clouds\AutoMLCloud\Service\JobProcessor.cs:line 395

**Comment by CESARDELATORRE** [comment]
I retried the PIPELINE run and it worked... weird.. ;)

![image](https://user-images.githubusercontent.com/1712635/83962402-e1109880-a851-11ea-98c5-7050fd0b6e7e.png)
